### ISSUE TITLE
ER diagram issues

### ISSUE THREAD

**Issue by liujiajun** [AY1920S2-CS2102-Team16/Food-Delivery-Service#59]
Issues
- `Reviews` does not have a key
- `CustomerCards` does not have a key
- Two `Earns` relations. Is that okay?

Things can't really be shown on ER model
- Each location should be used by either a restaurant or a customer but not both
- Each promotion should be either  by either a manager or a restaurant but not both

**Comment by yueyuu** [comment]
- [x] Add aggregation symbols
- [x] Rename `Earns` relations

**Comment by liujiajun** [comment]
A few new things 
1. FWS and PWS should have weak entity relationship towards works.
2. Salaries should have weak entity relation towards Riders. ( instead of PT or FT)
3. Change names of works relation to pworks (part time works). Same goes for all relations with the same names.
4. Add an attribute “id” to reviews, make it a key
5. Rename FWS to MWS and PWS to WWS
6. Remove `customercards`, add new relations `cards` and `registers` as shown in schema on **google docs** . Note there is key participation between customer and registers

**Comment by yueyuu** [comment]
Done
